apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-secure-app
  labels:
    app: my-secure-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-secure-app
  template:
    metadata:
      labels:
        app: my-secure-app
      annotations:
        # These annotations are where the Vault Magic happens!
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "internal-app"
        vault.hashicorp.com/agent-inject-secret-database-config.txt: "secret/my-app"
        # This formats the secret so the app can read it easily
        vault.hashicorp.com/agent-inject-template-database-config.txt: |
          {{- with secret "secret/my-app" -}}
          export DATABASE_PASSWORD="{{ .Data.data.password }}"
          {{- end -}}
    spec:
      serviceAccountName: vault-auth # Needed to prove who the pod is
      automountServiceAccountToken: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
      containers:
      - name: app
        image: nginx@sha256:0d17b565c37bcbd895e9d92315a05c1c3c9a29f762b011a10c54a66cd53c9b31
        imagePullPolicy: Always
        command:
          - "sh"
          - "-c"
          - "sleep 3600" # Keeps the container running so we can look inside
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 10001
          capabilities:
            drop:
              - ALL
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - "true"
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - "true"
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: secure-app-network-policy
spec:
  podSelector:
    matchLabels:
      app: my-secure-app
  policyTypes:
  - Ingress
  - Egress
